name: Scan

on:
  push:
    branches: ["main"]

jobs:
  scanit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install that thing
        run: composer require squizlabs/php_codesniffer

      - name: Run phpcs
        run: vendor/bin/phpcs .
